project:
  type: book
  output-dir: docs

book:
  title: "NFDI4Objects Knowledge Graph"
  subtitle: "Eine Einführung"
  repo-url: https://github.com/nfdi4objects/n4o-property-graph
  repo-actions:
    - source
  chapters:
    - index.qmd
    - property-graph.qmd
    - data-model.qmd
    - cypher.qmd
    - queries.qmd
    - cypher_mit_python.qmd
    - triple-store.qmd
    - architecture.qmd
  page-footer: 
    right: 
      - text: Datenschutz
        href: https://www.gbv.de/datenschutz
      - text: Impressum
        href: https://www.gbv.de/impressum
      - icon: github
        href: https://github.com/nfdi4objects/n4o-property-graph

tbl-cap-location: bottom
number-sections: false
number-depth: 1

format:
  html:
    theme: cosmo
    link-external-icon: true
