# Try with:
#
# docker compose -f docker-compose-graph.yml up --force-recreate -V

services:

  fuseki:
    image: ghcr.io/nfdi4objects/n4o-fuseki:main
    #ports:
    #  - "3031:3030"
    #volumes:
    #  - ./fuseki/logs:/fuseki/logs
    #  - ./fuseki/databases:/fuseki/databases
    #  - ./fuseki/log4j2.properties:/fuseki/log4j2.properties:ro
    networks:
      - n4o
    restart: always

  apis:
    image: ghcr.io/nfdi4objects/n4o-graph-apis:main
    ports:
      - ${PORT:-8000}:8000
    volumes:
      - ./config-apis.yml:/app/config.yaml:ro # ./config-apis.yml must exist!
      - ${STAGE:-./stage}:/app/stage:ro
    networks:
      - n4o

  importer:
    image: ghcr.io/nfdi4objects/n4o-graph-importer:main
    ports:
      - ${IMPORT:-5020}:5020
    volumes:
      - ${STAGE:-./stage}:/app/stage
      - ${DATA:-./data}:/app/data:ro
    networks:
      - n4o
    environment:
      - SPARQL=http://fuseki:3030/n4o

  converter:
    image: ghcr.io/nfdi4objects/lido-rdf-converter:main
    networks:
      - n4o

networks:
  n4o:
    driver: bridge
