---
title: Triple Store
---

Die im Knowledge-Graph zusammengeführten Daten werden zusammen mit weiteren
RDF-Daten in einem **Triple Store** zur verfügung gestellt und können per
**SPARQL** abgefragt werden.

*Dieser Dienst befindet sich noch im Aufbau*


## Grundlagen
Ein **Triple Store** ist eine [Graphendatenbank](https://de.wikipedia.org/wiki/Graphdatenbank), die auf Basis von [RDF](https://de.wikipedia.org/wiki/Resource_Description_Framework) Daten in Subjekt-Prädikat-Objekt Triples speichert. Das Subjekt und Objekt stellen die Knoten dar, die über ein Prädikat verbunden sind.


## Inhalt des Triple Store

- Alle in RDF angelieferten Daten (soweit syntaxktisch korrekt). Es ist also kein einheitliches Datenmodell vorgeschrieben! Aus den RDF-Daten werden lediglich Aussagen über Terminologien und Ontologien herausgefiltert

- Jede Lieferung ist ein Named Graph, so dass die Lieferungen sowohl einzeln, als auch in einem RDF-Graphen zusammengefasst abgefragt werden können.

- Unterstützte Ontologien und Terminologien sind ebenfalls als eigene Namend Graphs eingespielt, so dass sie für Abfragen verwendet werden können.


## Beispielabfragen

### Statistik aller Prädikate und ihrer Häufigkeit
```sparql
SELECT distinct ?pred WHERE {
  ?sub ?pred ?obj .
}
```

### Statistik aller Prädikate sortiert nach Anzahl der Prädikate
```sparql
SELECT distinct ?pre (COUNT(?pre) AS ?count) WHERE {
  ?s ?pre ?obj
} 
GROUP BY ?pre
ORDER BY DESC(?count)
```

### Statistik aller Objekte mit spezifischen Prädikat sortiert nach Anzahl der Subjekte
```sparql
SELECT distinct (COUNT(?s) AS ?count) ?obj WHERE {
  ?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?obj
} 
GROUP BY ?obj
ORDER BY DESC(?count)
```

