project:
  type: book
  output-dir: ../docs
  render:
    - "!*.md"

filters:
 - include-code-files

book:
  title: "NFDI4Objects Knowledge Graph"
  subtitle: "Handbuch für Nutzung und Management des N4O Graph"
  favicon: img/logo.png
  repo-url: https://github.com/nfdi4objects/n4o-graph
  language: de
  repo-subdir: manual
  repo-actions:
    - source
  chapters:
    - index.qmd
    - basics.qmd
    - sources.qmd
    - collections.qmd
    - terminologies.qmd
    - mappings.qmd
    - schema.qmd
    - cidoc-crm.qmd
    - usage.qmd
    - sparql.qmd
    - applications.qmd
    - import.qmd
    - architecture.qmd
    - status.qmd
    - references.qmd
  navbar:
    title: NFDI4**Objects Knowledge Graph**
    logo: img/logo.png
    logo-href: https://graph.nfdi4objects.net/
    left:
      - text: SPARQL 
        href: https://graph.nfdi4objects.net/sparql
      - text: Collections
        href: https://graph.nfdi4objects.net/collection/
      - text: Terminologies
        href: https://graph.nfdi4objects.net/terminology/
      - text: __Manual__
        href: ../
  page-footer: 
    left:
      - text: NFDI4Objects
        href: https://www.nfdi4objects.net/
    right: 
      - text: Datenschutz
        href: https://www.gbv.de/datenschutz
      - text: Impressum
        href: https://www.gbv.de/impressum
      - icon: github
        href: https://github.com/nfdi4objects/n4o-graph

toc: true
tbl-cap-location: bottom
number-sections: false
number-depth: 1

format:
  html:
    theme: cosmo
    link-external-icon: true
    include-before-body:
      text: |
        <script src="./js/common.js"></script>
        <script src="./js/codemirror.js"></script>
        <script src="./js/sparql.js"></script>
        <script src="./js/turtle.js"></script>
        <script src="./js/runmode.js"></script>
        <script src="./js/highlight.js"></script>
    css:
      - codemirror.css
      - style.css

