---
title: Grundlagen
subtitle: Wesentliche Grundbegriffe zum Verständnis des Knowledge Graphen
lang: de
---

Zur Nutzung des Knowledge Graphen ist das Verständnis einiger Grundbegriffe notwendig:

- Ein [Knowledge Graph] enthält Informationen in Form eines Graphen aus Knoten und Kanten.
  [Property Graph] und [Triple Store] sind zwei unterschiedliche Datenbanktechniken zur
  Verwaltung von Knowledge Graphen.
- Ein [Schema] definiert welche Art von Daten in einer Datenbank oder einem Datenformat erlaubt sind.
- [Vokabulare](#vokabular) sind vorgegebene Listen von Entitäten.
- Der [Datenbestand] ist der eigentliche Inhalt des Knowledge Graphen. Er stammt aus
  regelmäßig aktualisierten Lieferungen verschiedener [Sammlungen] von Forschungsdaten
  in festgelegten [Formaten](#datenformate).

Weitere technischen Details und Hintergründe finden sich im Kapitel zur [Systemarchitektur](architecture.qmd).

## Knowledge Graph

In einem **Knowledge Graph** (auch **Wissensgraph**) sind Informationen
strukturiert und stark miteinander vernetzt gespeichert. Ein Beispiel hierfür
ist ein Netzwerk aus Personen, die durch Verwandschaft und andere Beziehungen
miteinander verknüpft sind.  Jeder Graph besteht aus **Knoten** und **Kanten**.
So lassen sich beispielsweise Personen durch Knoten und Beziehungen durch Kanten
repräsentieren.

Weitere Details hängen von der technischen Umsetzung des Knowledge Graphen ab.
Die beiden am häufigsten verwendeten Datenbankmodelle sind
[**Property-Graphen**](#property-graphen) und das RDF-Datenmodell mit
**[Triple Stores](#triple-store)**. Darüber hinaus gibt es einige Knowledge
Graphen mit eigenem Datenbankmodell, beispielsweise
[Wikidata](https://www.wikidata.org/) auf Grundlage von des Wikibase-Modells.

Die Inhalte eines Knowledge Graphen besteht aus einem [Schema],
optional einigen [**Vokabularen**](#vokabular) und dem
**[Datenbestand]** als eigentlichem Datenbankinhalt.
Einzelne "Datensätze" gibt es aufgrund der Graphstruktur nicht.

## Datenbankmodelle

### Triple Store

Ein Triple Store ist eine [Graphendatenbank](https://de.wikipedia.org/wiki/Graphdatenbank) in der Daten dem [RDF-Modell](#rdf) nach in Form von so genannten Triplen gespeichert werden. Jedes **Tripel** entspricht in der Regel einer Kante im Graphen und besteht aus Subjekt, Prädikat und Objekt. Als Abfragesprache für RDF-Daten in Triple Stores dient [SPARQL](sparql.qmd).

### Property Graph

Property-Graphen dienen der Strukturierung, Speicherung und Auswertung
vernetzter Daten. Die Daten werden dabei nicht in tabellarischer Form (wie bei
einer Tabellenkalkulation oder bei SQL) oder in hierarchischer Form (wie bei
XML) sondern in Form eines **Graphen** gespeichert. Die Knoten und Kanten des
Graphen können jeweils **Labels** (Typen) haben und mit **Eigenschaften**
versehen sein. Zur Abfrage von Property-Graphen dient die Sprache
[Cypher](cypher.qmd). Eine genauere Erklärung liefert der Artikel
[Property-Graphen: eine kurze Einführung](https://jakobib.github.io/pgraphen2024/).

::: {.callout-tip appearance="minimal"}
Beispiele von Property-Graphen werden in diesem Handbuch im [Property Graph Exchange Format (PG)](https://pg-format.github.io/) dargestellt.
:::

## Datenbankinhalt

### Schema

Das Datenbankschema oder **Datenmodell** eines Knowledge Graphen bestimmt welche Arten von Knoten, Kanten und weiterer Inhalte im Graph enthalten sein dürfen. Da sich die Datenbankmodelle von [Property Graph] und [Triple Store] unterscheiden, gibt es für beide jeweils ein eigenes Schema. Beide Schemas basieren allerdings auf dem gemeinsamen abstrakten Datenmodell [CIDOC-CRM](crm.qmd). Details zu den Schemas finden sich im [Kapitel Datenbankschema](schema.qmd).

Neben dem Schema von Graphdatenbanken gibt Schemas zur Validierung der [Datenformate] gelieferter Daten und Vokabulare.

::: {.callout-tip appearance="minimal"}
Im Schema ist beispielsweise vorgegeben, dass es für Messungen Knoten der Klasse `E16_Measurement` und für Zeiträume Knoten der Klasse `E52_Time_Span` gibt.
:::


### Datenbestand

Der Datenbestand ist der eigentliche Inhalt des gemeinsamen Knowledge Graphen von NFDI4IObjekts. Er wird im Gegensatz zu [Schema] und [Vokabularen](#vokabular) laufend durch Lieferungen von [Sammlungen](#sammlung) Forschungsdaten aktualisiert, die in den Graphen integriert werden.

### Vokabular

Vokabulare sind vorgegebene Listen von Entitäten oder Werten. Sie sind in Form von Identifikatoren, Datentypen und/oder Knoten und Kanten zwar Teil des Knowledge-Graphen gehören aber eher nicht zum eigentlichen Datenbestand. Vokabulare werden nur in unregelmäßign Abständen und zentral aktualisiert. Sie dürfen nicht durch Lieferungen von [Sammlungen](#sammlungen) überschrieben werden. Weitere Informationen finden sich in den Kapiteln zu [Vokabularen](vocabularies.qmd) und zu [Mappings](mappings.qmd).

::: {.callout-tip title="Beispiele" appearance="minimal"}
Häufig verwendete Vokabulare sind die Gemeinsame Normdatei (GND), das Klassifizierungssystem Iconclass und die Normdateien des Getty Research Institute.
Darüber hinaus gibt es zahlreiche Spezial-Vokabulare wie zum Beispiel die Hornbostel-Sachs-Klassifikation der Musikinstrumente.
:::

### Sammlung

Der [Datenbestand] des Knowledge Graphen von NFDI4IObjekts ist in so genannte Sammlungen unterteilt. Einige Sammlungen bestehen aus einzelnen Datensätzen, andere aus einer zusammengefassten Lieferung von Daten. Weitere Informationen zu Sammlungen und Lieferungen finden sich im [Kapitel Datenquellen](sources.qmd).

## Datenformate

Zur Integration in den [Datenbestand] des Knowledge Graphen können Daten grundsätzlich in [LIDO] oder in [RDF] geliefert werden. Darüber hinaus gibt es spezielle Formate für [Vokabulare](vocabularies.qmd) und [Mappings](mappings.qmd).

#### LIDO

Lightweight Information Describing Objects (LIDO) ist ein XML-Format aus dem Museumsbereich (siehe [LIDO in der Formatdatenbank](http://format.gbv.de/lido)).

#### RDF

RDF-Daten können in verschiedenen Serialisierungen vorkommen, die sich verlustfrei ineinander überführen lassen (siehe [RDF in der Formatdatenbank](http://format.gbv.de/rdf)). Im Gegensatz zum allgemeinen Graph-Daten eines [Property Graphen](#knowledge-graph) enthalten RDF-Daten global eindeutige URIs als Identifikatoren. Außerdem lassen sich RDF-Daten aus unterschiedlichen Quellen immer zusammenführen. Sofern kein einheitliches [Schema] verwendet wird, ist das Ergebnis allerdings uneinheitlich.

