# Datenmodell {#sec-schema}

::: {.callout-warning appearance="important"}
Dieses Kapitel ist nichtmehr aktuell!
:::

Im Folgenden das Datenbankschema des Property Graphen beschrieben. Die
RDF-Daten im Triple-Store folgend dagegen bislang keinen Schema sondern werden
so eingespielt wie sie geliefert werden.

Als Sammlungsübergeifendes Datenmodell wird **[CIDOC-CRM (CRM)](cidoc-crm.qmd)**
verwendet. Weitere Ontologien müssen auf CRM gemappt werden. Darüber hinaus
werden eine Reihen von etablierten [Vokabularen](#sec-vocabularies) wie
ICONCLASS, GND und die LIDO-Terminologien unterstützt.

## Modellierung

::: {.callout-warning appearance="simple"}
Die Modellierung ist noch nicht abgeschlossen! Überlegungen zur Abbildung
von CRM in RDF [befinden sich hier](https://nfdi4objects.github.io/crm-rdf-ap/).
:::

### Entitäten und Knoten

Zwischenzeitlich gelöschte und umbenannte Klassen können weiterhin verwendet
werden, allerdings werden diese durch [Expansion](#expansion) auf die neueste
Form gemappt.

### Elementare Datentypen

Die folgende CRM-Klassen für elementare Datentypen werden *nicht* als Knoten-Label verwendet. Ihre Instanzen werden im Datenmodell stattdessen als Property-Werte abgebildet:

- [E59 Primitive Value](http://www.cidoc-crm.org/cidoc-crm/E59)
- [E60 Number](http://www.cidoc-crm.org/cidoc-crm/E60) für Zahlen
- [E62 String](http://www.cidoc-crm.org/cidoc-crm/E62) für Zeichenketten

Instanzen der folgenden CRM-Klassen werden ebenfalls *wenn möglich* nicht als Knoten sondern als Property-Werte abgebildet. Anderenfalls erfolgt die Expansion nur über die übergeordnete Klasse [E41 Appellation](http://www.cidoc-crm.org/cidoc-crm/E41):

- [E61 Time Primitive](http://www.cidoc-crm.org/cidoc-crm/E61) für Datums- und Zeitangaben
- [E94 Space Primitive](http://www.cidoc-crm.org/cidoc-crm/E94) für Koordinaten

### Relationen und Kanten

CRM-Properties (nicht zu verwechseln mit Eigenschaften im [Property-Graph
Datenbankmodell](#property-graph)) werden im Property-Graphen durch
Kanten-Label modelliert.

::: {.callout-warning appearance="simple"}
[Expansion] von Kanten-Label ist noch nicht umgesetzt!
:::

::: {.callout-warning appearance="simple"}
Inverse CRM-Properties sind noch nicht berücksichtigt!
:::

Eine Ausnahme bilden die folgenden CRM-Properties für [elementare
Datentypen](#elementare-datentypen), die stattdessen zu Property-Keys werden (siehe folgender Abschnitt).

## Beispiel

Folgender in CIDOC-CRM modellierter Teilgraph (in Turtle-Syntax):

```ttl
{{< include crm-example.ttl >}}
```

## Vokabulare

*Die konkrete Modellierung und Implementierung ist noch in Arbeit.*

Ausgewählte kontrollierte [Vokabulare](#sec-vocabularies) werden zentral in den Property Graphen eingespielt. Das Datenmodell dafür basiert auf CIDOC-CRM und SKOS mit folgenden Bestandteilen:

- Vokabulare haben die Property `uri` mit der BARTOC-URI des Vokabulars als Wert und die 
  Label `E32_Authority_Document` ([E32 Authority Document](https://cidoc-crm.org/html/cidoc_crm_v7.1.3_with_translations.html#E32)) sowie `ConceptScheme` zur Markierung, dass sie als Vokabular eingespielt wurden.

- Konzepte haben eine Property `uri` und können unterschiedliche Label haben. Der allgemein Fall ist `E55_Type`.
  ([E55 Type](https://cidoc-crm.org/html/cidoc_crm_v7.1.3_with_translations.html#E55)).
  Darüber hinaus erhalten sie das Label `Concept` zur Markierung, dass sie aus einem Vokabular statt aus einer
  Lieferung von Forschungsdaten stammen.

- Konzepte werden ihrem Vokabular mit dem Kanten-Label `inScheme` zugeordnet. Die entsprechende inverse CRM-Property
  [P71 lists](https://cidoc-crm.org/html/cidoc_crm_v7.1.3_with_translations.html#P71) wird *nicht* verwendet.

- Konzepte können mit den Kanten-Labeln `broader` miteinander verknüpft werden. Die entsprechende CRM-Property
  [P127 has broader term](https://cidoc-crm.org/html/cidoc_crm_v7.1.3_with_translations.html#P127) wird *nicht*
  verwendet.

- Konzepte können eine interne ID oder Notation haben (Property `notation`)

- Konzepte sollten Benennungen haben (Property `label` und `labelLang`)

Darüber könnten folgende CRM-Bestandteile eine Rolle spielen:

- [P150 defines typical part of](https://cidoc-crm.org/html/cidoc_crm_v7.1.3_with_translations.html#P150),
  ein Spezialfall von `skos:related`.
- [P2 has type](https://cidoc-crm.org/html/cidoc_crm_v7.1.3_with_translations.html#P2)
- [P137 exemplifies](https://cidoc-crm.org/html/cidoc_crm_v7.1.3_with_translations.html#P137)
  die inverse Relation von `skos:example`.

<!--
TODO: prefLabel, prefLabelLang

The Art & Architecture Thesaurus (E32) lists alcazars (E55). (http://vocab.getty.edu/page/aat/300006897)

-->

:::{.callout-note title="Beispiel"}
GND-Datensatz zu "Schleswig-Holstein":

```pg
gnd :ConceptScheme :E32_Authority_Document             # GND
  uri: http://bartoc.org/en/node/430

sh :Concept :E55_Type :E42_Identifier            # Schleswig-Holstein
  uri: https://d-nb.info/gnd/4052692-6

sh -> gnd :inScheme
```

<!--
type	http://terminology.lido-schema.org/identifier_type/uri	
value	https://d-nb.info/gnd/4052692-6
-->

