---
title: Vokabulare
subtitle: Listen gemeinsamer Entitäten
---

Vokabulare (auch bekannt als **Terminologien** oder Normdaten) sind vorgegebene Listen von Entitäten oder Werten. Jeder Eintrag hat einen eindeutigen Identifier, der in Daten aus [Sammlungen](collections.qmd) verwendet werden kann, um in unterschiedlichen Zusammenhängen auf die gleichen Dinge zu verweisen.

Vokabulare sind Teil des Knowledge Graphen, werden aber im Gegensatz zu Sammlungen zentral verwaltet. Grundlage ist zunächst ein Eintrag des Vokabulars in [BARTOC](https://bartoc.org). Eine Liste von unterstützen oder anderweitig relevanten Vokabularen in NFDI4Objects ist [als Teilmenge von BARTOC](https://bartoc.org/vocabularies?partOf=http://bartoc.org/en/node/18961) abrufbar.

Zur Vereinheitlichung von Daten, die unterschiedliche Vokabulare verwenden, müssen verschiedene Vokabulare aufeinander [gemappt werden](mappings.qmd). Dafür steht unter <https://coli-conc.gbv.de/cocoda/nfdi4objects/> eine Instanz der Mapping-Anwendung Cocoda zur Verfügung.

## Beispiele

Häufig verwendete Normdateien sind die [Gemeinsame Normdatei (GND)](https://bartoc.org/en/node/430), das Klassifizierungssystem [Iconclass](https://bartoc.org/en/node/459) und die Normdateien des Getty Research Institute. Darüber hinaus gibt es zahlreiche Spezial-Vokabulare wie zum Beispiel die [Hornbostel-Sachs-Klassifikation der Musikinstrumente](https://bartoc.org/en/node/1048).

Zu den Vokabularen gehören auch Ontologien, die sich in das [Datenbankschema](schema.qmd) des Knowledge Graphen integrieren oder darauf abbilden lassen. Die wichtigste Ontologie für den N4O Knowledge Graphen ist [CIDOC-CRM](cidoc-crm.qmd).

