---
title: Vokabulare
subtitle: Listen gemeinsamer Entitäten
---

Vokabulare (auch bekannt als Terminologien oder Normdaten) sind vorgegebene Listen von Entitäten oder Werten, auf die in anderen Daten verwiesen werden kann. Sie sind Teil des Knowledge Graphen, stammen aber nicht aus Datenlieferungen von [Sammlungen](basics.qmd#sammlungen) sondern werden zentral verwaltet.Grundlage für die kontrollierte Verwendung von Vokabularen im Knowledge Graph ist ein Eintrag in [BARTOC](https://bartoc.org). Eine Liste von unterstützen oder anderweitig relevanten Vokabularen in NFDI4Objects ist als Teilmenge von BARTOC [in einer Übersicht](https://nfdi4objects.github.io/n4o-terminologies/) verfügbar.

Auch wenn sich Vokabulare und Ontologien in der Regel bei genauerer Betrachtung unterscheiden lassen, sind die Grenzen mitunter nicht ganz klar.

Zur Vereinheitlichung von gelieferten Daten müssen verschiedene Vokabulare aufeinander abgebildet werden (siehe [Mappings](mappings.qmd)). Dafür steht unter <https://coli-conc.gbv.de/cocoda/nfdi4objects/> eine Instanz der Mapping-Anwendung Cocoda zur Verfügung.
